databases:
  - name: the-cinephile
    databaseName: the-cinephile
    user: the-cinephile
    plan: free

services:
  - type: web
    name: the-cinephile
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: the-cinephile
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: 2
        value: 2 # sensible default