databases:
  - name: the_cinephile_production
    databaseName: the_cinephile_production
    user: the_cinephile_production
    plan: free

services:
  - type: web
    name: the_cinephile_production
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "RAILS_ENV=production bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: the_cinephile_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default