default: &default
  adapter: postgresql
  encoding: unicode
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: the_cinephile_development
  username: postgres
  password: admin

test:
  <<: *default
  database: the_cinephile_test
  username: postgres
  password: admin

# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database

production:
  url: <%= ENV['DATABASE_URL'] %>
  database: the_cinephile_production
